
// {
//   "admin": false,
// "chapterTops": [],
//   "coinCount": 75,
// "collectIds": [
//   29080,
//   26578,
//   29082,
//   29081,
//   29109
//   ],
//   "email": "",
// "icon": "",
// "id": 164620,
// "nickname": "鸿蒙屌爆了",
// "password": "",
// "publicName": "鸿蒙屌爆了",
// "token": "",
// "type": 0,
// "username": "鸿蒙屌爆了"
// }

export class UserLoginBean {
	admin: boolean = false;
	chapterTops?: object[] = [];
	coinCount?: number = 0;
	collectIds?: number[] = [];
	email?: string = "";
	icon?: string = "";
	id?: number = 0;
	nickname?: string = "";
	password?: string = "";
	publicName?: string = "";
	token?: string = "";
	type?: number = 0;
	username?: string = "";
}
